# Generated by Django 4.1 on 2022-08-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('xabar', models.TextField()),
                ('sub', models.TextField()),
            ],
        ),
    ]
